# Generated by Django 5.0.3 on 2024-03-25 22:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TECNOLOGIA', 'Tecnologia'), ('ALIMENTO', 'Alimento'), ('CASA', 'Casa'), ('LAZER', 'Lazer'), ('JARDINAGEM', 'Jardinagem'), ('CONSTRUCAO', 'Construção'), ('OUTROS', 'Outros')], max_length=20)),
                ('value', models.FloatField()),
                ('desc', models.TextField(max_length=1000)),
                ('thumb', models.ImageField(upload_to='products_thumb')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
